apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "1.82.0"
    helm:
      values: |
        oauth:
          clientId:
            valueFrom:
              secretKeyRef:
                name: tailscale-oauth
                key: client-id
          clientSecret:
            valueFrom:
              secretKeyRef:
                name: tailscale-oauth
                key: client-secret
        operatorConfig:
          hostname: "k8s-operator"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
