apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    tailscale.com/proxy-class: "accept-routes"
  annotations:
    tailscale.com/tailnet-ip: "fd12:22ef:e152:0:2000:95:f868:c30e"
spec:
  type: ExternalName
  externalName: "placeholder"
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  ports:
    - port: 3000
      targetPort: 3000
