apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    tailscale.com/proxy-class: "accept-routes"
    tailscale.com/tailnet-fqdn: "grafana.railway.internal"
spec:
  type: ExternalName
  externalName: "placeholder"
  ports:
    - port: 3000
      targetPort: 3000
