name: Kubernetes Deploy

on:
  workflow_run:
    workflows:
      - Terraform
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    env:
      GKE_CLUSTER_NAME: ${{ vars.TF_VAR_PROJECT_ID }}-gke
      GKE_ZONE: us-central1-a
      GCP_PROJECT_ID: ${{ vars.TF_VAR_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME \
            --zone=$GKE_ZONE \
            --project=$GCP_PROJECT_ID

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Deploy Helm Charts
        run: |
          for chart in charts/*/; do
            if [ -d "$chart" ]; then
              chart_name=$(basename "$chart")
              echo "Deploying chart: $chart_name"
              helm upgrade --install "$chart_name" "$chart"
            fi
          done
